services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/src:/app/src
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

    environment:
      - PLACEHOLDER=placeholder
      - PORT=3006
    restart: always
    command:  npm run start
    ports:
      - "3006:3006"
  proxy:
    image: nginx
    volumes:
      - ./proxy/redirect_to_ssl.template:/etc/nginx/conf.d/redirect_to_ssl.template
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8080:80"
    links:
      - frontend
    environment:
      - DOLLAR=$$
      - NGINX_HOST=localhost
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/redirect_to_ssl.template > /etc/nginx/conf.d/default.conf && cat  /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    restart: always
